import jsPDF from "jspdf";
import "jspdf-autotable";
import * as XLSX from "xlsx";

// Extend jsPDF type for autotable
declare module "jspdf" {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
    lastAutoTable: { finalY: number };
  }
}

interface ReportConfig {
  title: string;
  subtitle?: string;
  generatedBy?: string;
  dateRange?: { from?: string; to?: string };
  confidential?: boolean;
}

interface TableSection {
  title?: string;
  headers: string[];
  rows: (string | number)[][];
}

interface SummaryCard {
  label: string;
  value: string | number;
}

const BRAND_COLOR: [number, number, number] = [30, 64, 175]; // blue-800
const HEADER_BG: [number, number, number] = [241, 245, 249]; // slate-100
const BORDER_COLOR: [number, number, number] = [203, 213, 225]; // slate-300

export function generatePDF(
  config: ReportConfig,
  summaryCards: SummaryCard[],
  tables: TableSection[]
) {
  const doc = new jsPDF("p", "mm", "a4");
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let y = 15;

  // --- Header ---
  doc.setFillColor(...BRAND_COLOR);
  doc.rect(0, 0, pageWidth, 32, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("L-Kurve", 14, 14);

  doc.setFontSize(14);
  doc.text(config.title.toUpperCase(), 14, 23);

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  const dateStr = `Generated: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`;
  doc.text(dateStr, pageWidth - 14, 14, { align: "right" });
  if (config.dateRange?.from || config.dateRange?.to) {
    const rangeStr = `Period: ${config.dateRange.from || "—"} to ${config.dateRange.to || "—"}`;
    doc.text(rangeStr, pageWidth - 14, 20, { align: "right" });
  }
  if (config.confidential) {
    doc.text("CONFIDENTIAL", pageWidth - 14, 26, { align: "right" });
  }

  y = 40;

  // --- Summary Cards ---
  if (summaryCards.length > 0) {
    doc.setTextColor(30, 41, 59);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("EXECUTIVE SUMMARY", 14, y);
    y += 6;

    const cardWidth = (pageWidth - 28 - (summaryCards.length - 1) * 4) / Math.min(summaryCards.length, 4);
    summaryCards.slice(0, 4).forEach((card, i) => {
      const x = 14 + i * (cardWidth + 4);
      doc.setFillColor(...HEADER_BG);
      doc.roundedRect(x, y, cardWidth, 18, 2, 2, "F");
      doc.setFontSize(7);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(100, 116, 139);
      doc.text(card.label, x + 4, y + 6);
      doc.setFontSize(13);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(30, 41, 59);
      doc.text(String(card.value), x + 4, y + 14);
    });
    y += 26;
  }

  // --- Tables ---
  tables.forEach((section) => {
    if (y > pageHeight - 40) {
      doc.addPage();
      y = 20;
    }

    if (section.title) {
      doc.setTextColor(30, 41, 59);
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.text(section.title.toUpperCase(), 14, y);
      y += 4;
    }

    doc.autoTable({
      startY: y,
      head: [section.headers],
      body: section.rows,
      margin: { left: 14, right: 14 },
      styles: { fontSize: 8, cellPadding: 3 },
      headStyles: {
        fillColor: BRAND_COLOR,
        textColor: [255, 255, 255],
        fontStyle: "bold",
      },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      didDrawPage: () => {
        // Footer on each page
        addFooter(doc, config);
      },
    });

    y = doc.lastAutoTable.finalY + 10;
  });

  // Footer on last page
  addFooter(doc, config);

  const filename = `${config.title.replace(/\s+/g, "_")}_${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}

function addFooter(doc: jsPDF, config: ReportConfig) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setDrawColor(...BORDER_COLOR);
  doc.line(14, pageHeight - 14, pageWidth - 14, pageHeight - 14);
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(148, 163, 184);
  doc.text(`L-Kurve LMS • ${config.title}`, 14, pageHeight - 9);
  if (config.generatedBy) {
    doc.text(`Generated by: ${config.generatedBy}`, pageWidth / 2, pageHeight - 9, { align: "center" });
  }
  const pageNumber = (doc as any).internal.getCurrentPageInfo().pageNumber;
  doc.text(`Page ${pageNumber}`, pageWidth - 14, pageHeight - 9, { align: "right" });
}

export function generateExcel(
  sheetName: string,
  headers: string[],
  rows: (string | number)[][],
  filename?: string
) {
  const ws = XLSX.utils.aoa_to_sheet([headers, ...rows]);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, sheetName.slice(0, 31));
  
  // Auto column widths
  const colWidths = headers.map((h, i) => {
    const maxLen = Math.max(h.length, ...rows.map(r => String(r[i] ?? "").length));
    return { wch: Math.min(maxLen + 2, 40) };
  });
  ws["!cols"] = colWidths;

  const fn = filename || `${sheetName.replace(/\s+/g, "_")}_${new Date().toISOString().slice(0, 10)}.xlsx`;
  XLSX.writeFile(wb, fn);
}

export function generateMultiSheetExcel(
  sheets: { name: string; headers: string[]; rows: (string | number)[][] }[],
  filename: string
) {
  const wb = XLSX.utils.book_new();
  sheets.forEach((sheet) => {
    const ws = XLSX.utils.aoa_to_sheet([sheet.headers, ...sheet.rows]);
    const colWidths = sheet.headers.map((h, i) => {
      const maxLen = Math.max(h.length, ...sheet.rows.map(r => String(r[i] ?? "").length));
      return { wch: Math.min(maxLen + 2, 40) };
    });
    ws["!cols"] = colWidths;
    XLSX.utils.book_append_sheet(wb, ws, sheet.name.slice(0, 31));
  });
  XLSX.writeFile(wb, filename);
}
